# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """$all$cmd_duration$time$sudo
$status$character"""

# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true


[status]
style = 'bold red'
format = '[\($status\)]($style) '
map_symbol = true
disabled = false

# Replace the '❯' symbol in the prompt with '➜'
#[character] # The name of the module we are configuring is 'character'
#success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[directory]
truncation_length = 0
truncate_to_repo = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[sudo]
format = '[\[sudo cached\]]($style) '
style = 'bold green'
disabled = false


[time]
disabled = false
format = '[$time]($style) '
time_format = '%T'
